// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolProject.infraStructure.Data;

#nullable disable

namespace SchoolProject.infraStructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250429115616_AddInstractorSeedingData")]
    partial class AddInstractorSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.Property<int>("DID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DID"));

                    b.Property<string>("DNameAR")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DNameEN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InsManager")
                        .HasColumnType("int");

                    b.HasKey("DID");

                    b.HasIndex("InsManager")
                        .IsUnique()
                        .HasFilter("[InsManager] IS NOT NULL");

                    b.ToTable("departments", "Dep");

                    b.HasData(
                        new
                        {
                            DID = 1,
                            DNameAR = "الهندسة",
                            DNameEN = "Engineering"
                        },
                        new
                        {
                            DID = 2,
                            DNameAR = "الطب",
                            DNameEN = "Medicine"
                        },
                        new
                        {
                            DID = 3,
                            DNameAR = "التجارة",
                            DNameEN = "Commerce"
                        },
                        new
                        {
                            DID = 4,
                            DNameAR = "الحقوق",
                            DNameEN = "Law"
                        },
                        new
                        {
                            DID = 5,
                            DNameAR = "الصيدلة",
                            DNameEN = "Pharmacy"
                        },
                        new
                        {
                            DID = 6,
                            DNameAR = "طب الأسنان",
                            DNameEN = "Dentistry"
                        },
                        new
                        {
                            DID = 7,
                            DNameAR = "علوم الحاسب",
                            DNameEN = "Computer Science"
                        },
                        new
                        {
                            DID = 8,
                            DNameAR = "الآداب",
                            DNameEN = "Arts"
                        },
                        new
                        {
                            DID = 9,
                            DNameAR = "الزراعة",
                            DNameEN = "Agriculture"
                        },
                        new
                        {
                            DID = 10,
                            DNameAR = "التربية",
                            DNameEN = "Education"
                        },
                        new
                        {
                            DID = 11,
                            DNameAR = "التمريض",
                            DNameEN = "Nursing"
                        },
                        new
                        {
                            DID = 12,
                            DNameAR = "العلوم",
                            DNameEN = "Science"
                        },
                        new
                        {
                            DID = 13,
                            DNameAR = "الطب البيطري",
                            DNameEN = "Veterinary Medicine"
                        },
                        new
                        {
                            DID = 14,
                            DNameAR = "التربية الرياضية",
                            DNameEN = "Physical Education"
                        },
                        new
                        {
                            DID = 15,
                            DNameAR = "السياحة والفنادق",
                            DNameEN = "Tourism and Hotels"
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.DepartmentSubject", b =>
                {
                    b.Property<int>("SubID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectSubID")
                        .HasColumnType("int");

                    b.HasKey("SubID", "DepartmentID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("SubjectSubID");

                    b.ToTable("departmentSubjects", "DepSub");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Ins_Subject", b =>
                {
                    b.Property<int>("SubId")
                        .HasColumnType("int");

                    b.Property<int>("InsId")
                        .HasColumnType("int");

                    b.HasKey("SubId", "InsId");

                    b.HasIndex("InsId");

                    b.ToTable("Ins_Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Instructor", b =>
                {
                    b.Property<int>("InsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("ENameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("InsId");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Instructor");

                    b.HasData(
                        new
                        {
                            InsId = 1,
                            Address = "القاهرة",
                            DepartmentID = 9,
                            ENameAr = "أحمد علي",
                            ENameEn = "Ahmed Ali",
                            Position = "أستاذ",
                            Salary = 12000m
                        },
                        new
                        {
                            InsId = 2,
                            Address = "الإسكندرية",
                            DepartmentID = 1,
                            ENameAr = "منى حسن",
                            ENameEn = "Mona Hassan",
                            Position = "معيد",
                            Salary = 8000m,
                            SupervisorId = 2
                        },
                        new
                        {
                            InsId = 3,
                            Address = "طنطا",
                            DepartmentID = 10,
                            ENameAr = "سعيد عبد الله",
                            ENameEn = "Saeed Abdullah",
                            Position = "دكتور",
                            Salary = 11000m
                        },
                        new
                        {
                            InsId = 4,
                            Address = "المنصورة",
                            DepartmentID = 4,
                            ENameAr = "فاطمة محمد",
                            ENameEn = "Fatma Mohamed",
                            Position = "أستاذ مساعد",
                            Salary = 9500m,
                            SupervisorId = 3
                        },
                        new
                        {
                            InsId = 5,
                            Address = "الجيزة",
                            DepartmentID = 7,
                            ENameAr = "علي إبراهيم",
                            ENameEn = "Ali Ibrahim",
                            Position = "معيد",
                            Salary = 7500m
                        },
                        new
                        {
                            InsId = 6,
                            Address = "أسيوط",
                            DepartmentID = 3,
                            ENameAr = "نهى محمود",
                            ENameEn = "Noha Mahmoud",
                            Position = "دكتور",
                            Salary = 10000m,
                            SupervisorId = 5
                        },
                        new
                        {
                            InsId = 7,
                            Address = "سوهاج",
                            DepartmentID = 1,
                            ENameAr = "مصطفى عبد الرحمن",
                            ENameEn = "Mostafa Abdelrahman",
                            Position = "أستاذ",
                            Salary = 13000m
                        },
                        new
                        {
                            InsId = 8,
                            Address = "بورسعيد",
                            DepartmentID = 2,
                            ENameAr = "إيمان السيد",
                            ENameEn = "Eman ElSayed",
                            Position = "مدرس مساعد",
                            Salary = 9000m,
                            SupervisorId = 7
                        },
                        new
                        {
                            InsId = 9,
                            Address = "دمياط",
                            DepartmentID = 5,
                            ENameAr = "طارق حمدي",
                            ENameEn = "Tarek Hamdy",
                            Position = "معيد",
                            Salary = 7800m
                        },
                        new
                        {
                            InsId = 10,
                            Address = "الفيوم",
                            DepartmentID = 3,
                            ENameAr = "هالة عبد الفتاح",
                            ENameEn = "Hala AbdelFattah",
                            Position = "مدرس",
                            Salary = 8600m,
                            SupervisorId = 9
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Student", b =>
                {
                    b.Property<int>("StudID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("NameAR")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("StudID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("students", "Stud");

                    b.HasData(
                        new
                        {
                            StudID = 1,
                            Address = "New York",
                            DepartmentID = 1,
                            NameAR = "جون سميث",
                            NameEN = "John Smith",
                            Phone = "1234567890"
                        },
                        new
                        {
                            StudID = 2,
                            Address = "Cairo",
                            DepartmentID = 2,
                            NameAR = "علي أحمد",
                            NameEN = "Ali Ahmed",
                            Phone = "9876543210"
                        },
                        new
                        {
                            StudID = 3,
                            Address = "Alexandria",
                            NameAR = "سارة كمال",
                            NameEN = "Sara Kamal",
                            Phone = "01112345678"
                        },
                        new
                        {
                            StudID = 4,
                            Address = "Giza",
                            DepartmentID = 1,
                            NameAR = "فاطمة عادل",
                            NameEN = "Fatma Adel",
                            Phone = "01234567890"
                        },
                        new
                        {
                            StudID = 5,
                            Address = "Tanta",
                            DepartmentID = 3,
                            NameAR = "محمد طارق",
                            NameEN = "Mohamed Tarek",
                            Phone = "01098765432"
                        },
                        new
                        {
                            StudID = 6,
                            Address = "Mansoura",
                            DepartmentID = 2,
                            NameAR = "نور حسن",
                            NameEN = "Nour Hassan",
                            Phone = "01555555555"
                        },
                        new
                        {
                            StudID = 7,
                            Address = "Aswan",
                            NameAR = "يوسف صالح",
                            NameEN = "Yousef Saleh",
                            Phone = "01111111111"
                        },
                        new
                        {
                            StudID = 8,
                            Address = "Ismailia",
                            DepartmentID = 1,
                            NameAR = "ليلى مصطفى",
                            NameEN = "Laila Mostafa",
                            Phone = "01222222222"
                        },
                        new
                        {
                            StudID = 9,
                            Address = "Zagazig",
                            DepartmentID = 2,
                            NameAR = "هاني عمر",
                            NameEN = "Hani Omar",
                            Phone = "01033333333"
                        },
                        new
                        {
                            StudID = 10,
                            Address = "Luxor",
                            DepartmentID = 3,
                            NameAR = "منى إيهاب",
                            NameEN = "Mona Ehab",
                            Phone = "01044444444"
                        },
                        new
                        {
                            StudID = 11,
                            Address = "Fayoum",
                            DepartmentID = 2,
                            NameAR = "كريم نبيل",
                            NameEN = "Kareem Nabil",
                            Phone = "01255555555"
                        },
                        new
                        {
                            StudID = 12,
                            Address = "Minya",
                            DepartmentID = 1,
                            NameAR = "أميرة سمير",
                            NameEN = "Amira Samir",
                            Phone = "01166666666"
                        },
                        new
                        {
                            StudID = 13,
                            Address = "Qena",
                            NameAR = "أسامة إبراهيم",
                            NameEN = "Osama Ibrahim",
                            Phone = "01577777777"
                        },
                        new
                        {
                            StudID = 14,
                            Address = "Damanhur",
                            DepartmentID = 3,
                            NameAR = "نادين شريف",
                            NameEN = "Nadine Sherif",
                            Phone = "01088888888"
                        },
                        new
                        {
                            StudID = 15,
                            Address = "Suez",
                            DepartmentID = 2,
                            NameAR = "حسام علي",
                            NameEN = "Hossam Ali",
                            Phone = "01299999999"
                        },
                        new
                        {
                            StudID = 16,
                            Address = "Beni Suef",
                            DepartmentID = 1,
                            NameAR = "رنا فتحي",
                            NameEN = "Rana Fathy",
                            Phone = "01012121212"
                        },
                        new
                        {
                            StudID = 17,
                            Address = "Damietta",
                            NameAR = "أحمد ياسين",
                            NameEN = "Ahmed Yassin",
                            Phone = "01123232323"
                        },
                        new
                        {
                            StudID = 18,
                            Address = "El Mahalla",
                            DepartmentID = 2,
                            NameAR = "تامر عصام",
                            NameEN = "Tamer Essam",
                            Phone = "01534343434"
                        },
                        new
                        {
                            StudID = 19,
                            Address = "Kafr El-Sheikh",
                            DepartmentID = 3,
                            NameAR = "شيماء فاروق",
                            NameEN = "Shaimaa Farouk",
                            Phone = "01045454545"
                        },
                        new
                        {
                            StudID = 20,
                            Address = "Port Said",
                            DepartmentID = 1,
                            NameAR = "زياد عادل",
                            NameEN = "Ziad Adel",
                            Phone = "01256565656"
                        },
                        new
                        {
                            StudID = 21,
                            Address = "Sohag",
                            DepartmentID = 2,
                            NameAR = "ندى إبراهيم",
                            NameEN = "Nada Ibrahim",
                            Phone = "01167676767"
                        },
                        new
                        {
                            StudID = 22,
                            Address = "Matruh",
                            NameAR = "عمر رضا",
                            NameEN = "Omar Reda",
                            Phone = "01578787878"
                        },
                        new
                        {
                            StudID = 23,
                            Address = "Beheira",
                            DepartmentID = 3,
                            NameAR = "آية مصطفى",
                            NameEN = "Aya Mostafa",
                            Phone = "01089898989"
                        },
                        new
                        {
                            StudID = 24,
                            Address = "Gharbia",
                            DepartmentID = 1,
                            NameAR = "محمود خالد",
                            NameEN = "Mahmoud Khaled",
                            Phone = "01290909090"
                        },
                        new
                        {
                            StudID = 25,
                            Address = "Qalyubia",
                            DepartmentID = 2,
                            NameAR = "ريم يونس",
                            NameEN = "Reem Younis",
                            Phone = "01111122333"
                        },
                        new
                        {
                            StudID = 26,
                            Address = "Sharqia",
                            NameAR = "باسل عماد",
                            NameEN = "Bassel Emad",
                            Phone = "01522233444"
                        },
                        new
                        {
                            StudID = 27,
                            Address = "Red Sea",
                            DepartmentID = 3,
                            NameAR = "فرح حاتم",
                            NameEN = "Farah Hatem",
                            Phone = "01033344555"
                        },
                        new
                        {
                            StudID = 28,
                            Address = "New Valley",
                            DepartmentID = 1,
                            NameAR = "مصطفى عمرو",
                            NameEN = "Mostafa Amr",
                            Phone = "01244455666"
                        },
                        new
                        {
                            StudID = 29,
                            Address = "North Sinai",
                            DepartmentID = 2,
                            NameAR = "جنى حسام",
                            NameEN = "Jana Hossam",
                            Phone = "01155566777"
                        },
                        new
                        {
                            StudID = 30,
                            Address = "South Sinai",
                            NameAR = "أدهم فادي",
                            NameEN = "Adham Fady",
                            Phone = "01566677888"
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.StudentSubjects", b =>
                {
                    b.Property<int>("SubID")
                        .HasColumnType("int");

                    b.Property<int>("StudID")
                        .HasColumnType("int");

                    b.Property<int>("StudSubID")
                        .HasColumnType("int");

                    b.Property<decimal?>("grade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SubID", "StudID");

                    b.HasIndex("StudID");

                    b.ToTable("studentSubjects", "StuSub");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Subject", b =>
                {
                    b.Property<int>("SubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubID"));

                    b.Property<int?>("Period")
                        .HasColumnType("int");

                    b.Property<string>("SubjectNameAR")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubjectNameEN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SubID");

                    b.ToTable("subjects", "Sub");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Instructor", "Instructor")
                        .WithOne("DepartmentManager")
                        .HasForeignKey("SchoolProject.Data.Entities.Department", "InsManager")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.DepartmentSubject", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany("DepartmentSubjects")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany("DepartmetsSubjects")
                        .HasForeignKey("SubjectSubID");

                    b.Navigation("Department");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Ins_Subject", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Instructor", "Instructor")
                        .WithMany("Ins_Subjects")
                        .HasForeignKey("InsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany("Ins_Subjects")
                        .HasForeignKey("SubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Instructor", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Instructor", "Supervisor")
                        .WithMany("Instructors")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Student", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.StudentSubjects", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("SubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.Navigation("DepartmentSubjects");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Instructor", b =>
                {
                    b.Navigation("DepartmentManager");

                    b.Navigation("Ins_Subjects");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Student", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Subject", b =>
                {
                    b.Navigation("DepartmetsSubjects");

                    b.Navigation("Ins_Subjects");

                    b.Navigation("StudentsSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
